error: add support for `std::system_error` passthrough
1. `blue_sky::error` can be constructed directly from `system_error`.

2.  error categories registry recognizes system error categories, hence
system errors can be packed to `error::box`.