error: allow constructing from variant & expected, improve ctors dispatch
1. Deny implicit conversion chain: some type -> bool/int -> err. Do this
   by introducing two types `quiet_flag` that can be constructed only
   from exactly bool value, and `raw_code` - from integral type.

2. Remove `success_tag` & `quiet_fail_tag`. Quiet success result now
   equals `quiet_flag(true)` and quiet fail = `quiet_flag(false)`.
   Hence, both have same type `quiet_flag`.

3. Implement new constructor that can initialize error from
   `std::variant` (or type derived from it) or `exepcted`, if they can
   carry `error` or `error::box` value.

4. Implement error-specific `is_constructible` trait that checks private
   constructors (`std::is_constructible` results in always true value because
   error has perfect-forwarding public constructor).
   This trait is used by `error::quiet()` and `error::eval()` leading to
   much greater flexibility & code simplification in latter case.