transaction: link/node transactions return `tr_result`, remove simple transaction
Rationale for this commit is that due to drawback of `caf::result`
constructors design it doesn't play well with `error` and `error::box`.
Trying to provide generc support for async transactions returning leads
to compilation errors.

1. Link & node transaction returns `tr_result::box` instead of
   `error::box`. The former can carry the latter.

2. Kernel's queue changed to process `transaction` instead of
   `simple_transaction`.

3. Had to move queue actor definition to separate TU because including
   `propdict` serialization code with `cafbind.h` seems to break smth
   inside middleman compilation.

[NOTE] CAF 0.18 has refactored `caf::result` as a sum type that expect
to fix this constructor issue. Maybe can undo these changes after
switching to 0.18.