error: add handy macro for `eval` and `eval_safe` to reduce lambda buzz
For common case when there's a need to evaluate several lambdas or one
scope and return if error happened.