error: refactor, switch to `std::runtime_error` composition
Goal of this refactoring is to optimize error construction inside tight
loops for common cases when it only holds `error_code` without additional
custom message (including cases when `OK` status is returned for
successfull operations).

Price for performance is slightly increased  memory footprint (due to
additional flag in std::optional) + noexcept guarantee
is lost for copy constructor (but errors aren't supposed to be
extensively copied anyway).

1. Remove inheritance from `std::runtime_error` and switch to
composition - it's instance using `std::optional`. `runtime_error` is
primarily used as exception-safe string that carries optional error
message.

2. `runtime_error` is only initialized in certain conditions (when custom
   error message is specifed for ex).

3. `error::box` also holds custom message string inside `std::optional`

4. Add `noexcept` specifiers where applicable.

5. Add `eval_safe_quiet()` that is similar to `eval_safe()` but produces
   quiet errors.

6. Remove unused included headers.